### PR TITLE
build: only include the needed parts of the Rails meta-gem

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by bf4** [comment]
Huh, Gemfile.lock shouldn't be in version control for a gem.  I didn't check. I'll regenerate the lockfile

**Comment by bensheldon** [comment]
Thanks!

> Huh, Gemfile.lock shouldn't be in version control for a gem.

I'm an iconoclast on that :-) Repeatable development builds are important to me, and there is a long-tail of transitive dependencies that are easily captured by committing the lockfile.

**Comment by bf4** [comment]
> I'm an iconoclast on that

Well, as long as it's intentional I suppose.  In my own experience, finding any transitive dependencies which cause failures due to not having a Gemfile.lock is a feature :)

I've updated the Gemfile.lock and amended my commit and force pushed

**Comment by bensheldon** [comment]
It's more about having repeatable builds, especially if there's a risk that I won't be continuously developing the gem. I don't like coming back to a project 1+ years later and discovering that something is now broken and not being sure what changed.

And I think most first-time contributors are likely to be coming from an application-development context where dependencies are locked, and I want to avoid the "I can't get this gem to build"-type issues

I note transitive dependencies because usually the counterargument is: if you want to lock gem development dependencies, specify them in the gemspec.  And the counter-counter argument to that is: there are so many transitive dependencies that capturing them all is not effortless. And at which point, by capturing them all, it recreates the lockfile so just use that directly.

The argument I usually see about why not to commit the lockfile is: because gems may have to be tested/built in lots of different environments, and the lockfile precludes that. But I generally believe:

- A gem developer (me) likely spends 90% of their time in a single development context (version of Ruby, dependencies, etc.), so optimize for that.
- Delete and recreate the lockfile (and then don't commit it) when working in the other 10% of environments or in matrixed-CI builds.

(And thanks for being my foil here; I have thinking of writing a book about Rails Engine development 🤔 )

**Comment by bensheldon** [comment]
Released this 🎉 https://github.com/bensheldon/activerecord-has_some_of_many/releases/tag/v1.2.0

**Comment by bf4** [comment]
> (And thanks for being my foil here; I have thinking of writing a book about Rails Engine development 🤔 )

I'd happily read/review that. Rails Engines/Railties (and ActiveSupport hooks) are powerful and important for gem devs, but often understanding of them comes through pain and/or just reading the source code :)  e.g. configuring initializer order, isolation context, lazy loading, etc...

I think there's a limit to the back and forth here, but a middle ground would be to have a `gemfiles` folder with e.g. `gemfiles/Gemfile_7_0`, `gemfiles/Gemfile_7_0.lock` and you're expected by default to maybe `bundle config --local gemfile gemfiles/Gemfile_7_0` for local dev, and CI runs `BUNDLE_GEMFILE=gemfiles/Gemfile_7_0` and such in a matrix, as needed. That ways you can track dependencies per some context and leave the root without a Gemfile.lock. Shrug :-D

My own approach is something like
- gemspec only has runtime required for executing gem and development things for running tests
- Gemfile has any bonus conf, like debugging tools or platform or version specific stuff

**Pull request merged**
